### ISSUE TITLE
Deploy Aragon-node-list as a plugin against testnet aragon

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/aragon-node-list#19]
the goal here is to test deployment not on mainnet, following this we will move to repeating the process on mainnet as soon as possible. 

deadline: 10/7/18
new deadline: 11/14/2018

**Comment by sebohe** [comment]
I have been trying to deploy the althea aragon plugin to no avail. I opened some issues and will wait for the replies:
https://github.com/aragon/aragon-cli/issues/265
https://github.com/aragon/aragon-cli/issues/266
https://github.com/aragon/aragon-cli/issues/267

**Comment by sebohe** [comment]
Punch card list:
- Publish to the apm.
- install to new dao using this branch: https://github.com/aragon/aragon-cli/pull/270

**Comment by sebohe** [comment]
~~Publish to the apm.~~

https://github.com/althea-mesh/aragon-node-list/commit/929b22d05c8d2dfb48ff7421f85c04c55c58c131

**Comment by sebohe** [comment]
The vote appeared on the the dao. But I don't see the app in the permissions or app list on the UI or from the cli:
![2018-11-12-135609_1366x768_scrot](https://user-images.githubusercontent.com/10123236/48431643-78932f80-e772-11e8-9fac-8f8e4284af20.png)

**Comment by sebohe** [comment]
Current task is getting the UI to show up. This first requires finding out the proxy address of the althea app. Then granting it permission with acl and using the following:
`dao acl create [dao] [appAddr] [roleName] [entityAddr] [permissionManagerAddr]`

**Comment by sebohe** [comment]
Deadline: 16/Nov/2018
